dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.1
protocols = lmtp
listen = *
mail_driver = maildir
mail_path = /var/mail/verification
first_valid_uid = 1000
first_valid_gid = 1000
service lmtp {
  inet_listener lmtp {
    port = 24
  }
}
protocol lmtp {
  postmaster_address = postmaster@mailproof.test
}
userdb static {
  allow_all_users = yes
  fields {
    uid = 1000
    gid = 1000
    home = /var/mail/verification
  }
}
passdb static {
  fields {
    password = nopassword
  }
}
